### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by Mcilie** [defund/pearl#5]
When I run pearl.py this happens

Traceback (most recent call last):
  File "/home/mcist-9013/Desktop/pearl-master/pearl/pearl.py", line 66, in <module>
    Pearl().run()
  File "/home/mcist-9013/Desktop/pearl-master/pearl/pearl.py", line 13, in __init__
    self.load_commands()
  File "/home/mcist-9013/Desktop/pearl-master/pearl/pearl.py", line 37, in load_commands
    spec.loader.exec_module(handler)
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/mcist-9013/Desktop/pearl-master/pearl/plugins/user.py", line 2, in <module>
    from firebase_admin import firestore
  File "/home/mcist-9013/.local/lib/python3.5/site-packages/firebase_admin/firestore.py", line 22, in <module>
    from google.cloud import firestore # pylint: disable=import-error,no-name-in-module
  File "/home/mcist-9013/.local/lib/python3.5/site-packages/google/cloud/firestore.py", line 18, in <module>
    from google.cloud.firestore_v1beta1 import __version__
  File "/home/mcist-9013/.local/lib/python3.5/site-packages/google/cloud/firestore_v1beta1/__init__.py", line 20, in <module>
    from google.cloud.firestore_v1beta1 import types
  File "/home/mcist-9013/.local/lib/python3.5/site-packages/google/cloud/firestore_v1beta1/types.py", line 23, in <module>
    from google.cloud.firestore_v1beta1.proto import firestore_pb2
  File "/home/mcist-9013/.local/lib/python3.5/site-packages/google/cloud/firestore_v1beta1/proto/firestore_pb2.py", line 2433, in <module>
    _sym_db.RegisterServiceDescriptor(_FIRESTORE)
AttributeError: 'SymbolDatabase' object has no attribute 'RegisterServiceDescriptor'

**Comment by defund** [comment]
Hi, if you want to use the firebase module, you'll need to create a project and include an authentication file. If you're just playing around with Pearl, I would recommend using the 4 basic modules from the quickstart guide. Thanks!
